### PR TITLE
 lafi

### PR DESCRIPTION
**Pull request by HayaLafi**
haya lafi

### CODE REVIEW

**Comment by omartuwaiq** [comment]
Please submit your css sheet so I can check your work.

**Comment by omartuwaiq** [comment]
Please post the css sheet so I can see how you styled it thank you

**Comment by HayaLafi** [comment]
في جمعة، ١٥ أكتوبر، ٢٠٢١ في ٩:٣١ م، كتب omartuwaiq ***@***.***
>:

I downloaded it here
>

**Comment by omartuwaiq** [comment]
Good job thank for posting the CSS page Haya

**Pull request closed without merging**
